spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/sale?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect